import { ExternalLink, RefreshCw } from "lucide-react";

import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export type Connection = "checking" | "ok" | "unconfigured" | "error";

const DOT: Record<Connection, string> = {
  checking: "bg-subtle animate-pulse",
  ok: "bg-success",
  unconfigured: "bg-warning",
  error: "bg-destructive",
};

const LABEL: Record<Connection, string> = {
  checking: "Checking…",
  ok: "Connected",
  unconfigured: "Not connected",
  error: "Backend unreachable",
};

/**
 * Status as a dot plus a word.
 *
 * The colour alone would not carry it - the panel is 400px of browser chrome
 * a user glances at, and colour is the first thing a glance gets wrong.
 */
export function StatusDot({
  state,
  withLabel,
}: {
  state: Connection;
  withLabel?: boolean;
}) {
  return (
    <span className="inline-flex items-center gap-1.5" title={LABEL[state]}>
      <span className={cn("size-1.5 shrink-0 rounded-full", DOT[state])} />
      {withLabel && (
        <span className="text-muted-foreground text-[11px]">{LABEL[state]}</span>
      )}
      {!withLabel && <span className="sr-only">{LABEL[state]}</span>}
    </span>
  );
}

export function PanelHeader({
  state,
  onRefresh,
  portalUrl,
}: {
  state: Connection;
  onRefresh: () => void;
  portalUrl: string;
}) {
  return (
    <header className="bg-card flex h-12 shrink-0 items-center gap-2 border-b px-3">
      {/* public/phoenix-avatar.png, generated by `npm run brand`. */}
      <img src="/phoenix-avatar.png" alt="" className="size-9 shrink-0" />
      <span className="text-base font-semibold tracking-tight">
        {/* Same stops as the portal's Brand: the phoenix's gold, orange and red. */}
        <span className="bg-linear-to-r from-[#f78d24] via-[#f4562c] to-[#d32127] bg-clip-text text-transparent">
          Phoenix
        </span>
        <span className="text-primary">Eye</span>
      </span>

      <StatusDot state={state} />

      <div className="ml-auto flex items-center gap-0.5">
        <Button
          size="icon-xs"
          variant="ghost"
          aria-label="Re-check the connection"
          onClick={onRefresh}
        >
          <RefreshCw className={cn(state === "checking" && "animate-spin")} />
        </Button>
        <Button size="icon-xs" variant="ghost" asChild aria-label="Open the web portal">
          <a href={portalUrl} target="_blank" rel="noreferrer">
            <ExternalLink />
          </a>
        </Button>
      </div>
    </header>
  );
}

export function PanelFooter({
  state,
  portalUrl,
  version,
}: {
  state: Connection;
  portalUrl: string;
  version: string;
}) {
  return (
    <footer className="bg-card flex shrink-0 items-center gap-2 border-t px-3 py-2">
      <StatusDot state={state} withLabel />
      <span className="text-subtle ml-auto text-[11px] tabular-nums">v{version}</span>
      <a
        href={portalUrl}
        target="_blank"
        rel="noreferrer"
        className="text-primary text-[11px] font-medium hover:underline"
      >
        Portal
      </a>
    </footer>
  );
}

/** A labelled group inside a tab, so a 400px column still has a structure. */
export function Section({
  title,
  action,
  children,
}: {
  title: string;
  action?: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <section className="space-y-2">
      <div className="flex items-center gap-2">
        <h2 className="text-muted-foreground text-[11px] font-semibold tracking-wide uppercase">
          {title}
        </h2>
        {action && <span className="ml-auto">{action}</span>}
      </div>
      {children}
    </section>
  );
}

/** Nothing to show, said in one line with an icon rather than a bare sentence. */
export function EmptyNote({
  icon: Icon,
  children,
}: {
  icon: React.ComponentType<{ className?: string }>;
  children: React.ReactNode;
}) {
  return (
    <div className="text-muted-foreground flex flex-col items-center gap-2 rounded-xl border border-dashed px-3 py-6 text-center">
      <Icon className="size-4" />
      <p className="text-[11px] leading-relaxed text-balance">{children}</p>
    </div>
  );
}
